service: autonomy-guard

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    AG_DATABASE_URL: ${env:AG_DATABASE_URL, 'sqlite+aiosqlite:////tmp/autonomy_guard.db'}
    AG_DEBUG: "False"

functions:
  api:
    handler: autonomy_guard.main.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
